// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAp0u6QyDVfrLlev6snRRdOu8jT9LKXwS4',
//     appId: '1:880329077950:web:e8b79e55aaabbe9a475aef',
//     messagingSenderId: '880329077950',
//     projectId: 'traveladminapp',
//     authDomain: 'traveladminapp.firebaseapp.com',
//     storageBucket: 'traveladminapp.firebasestorage.app',
//     measurementId: 'G-VQP0ESJ14P',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCupZRJY8-8kVVIPWf3lqJO9Jfihcyo9aI',
//     appId: '1:880329077950:android:9816fde669aa9b2c475aef',
//     messagingSenderId: '880329077950',
//     projectId: 'traveladminapp',
//     storageBucket: 'traveladminapp.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBl_5bT3HO4bAmceQDsKAwrcyx-0StVhBc',
//     appId: '1:880329077950:ios:6da159faeb2a5aaa475aef',
//     messagingSenderId: '880329077950',
//     projectId: 'traveladminapp',
//     storageBucket: 'traveladminapp.firebasestorage.app',
//     iosBundleId: 'com.example.adminProject',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBl_5bT3HO4bAmceQDsKAwrcyx-0StVhBc',
//     appId: '1:880329077950:ios:6da159faeb2a5aaa475aef',
//     messagingSenderId: '880329077950',
//     projectId: 'traveladminapp',
//     storageBucket: 'traveladminapp.firebasestorage.app',
//     iosBundleId: 'com.example.adminProject',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAp0u6QyDVfrLlev6snRRdOu8jT9LKXwS4',
//     appId: '1:880329077950:web:d9307b3a6826b7b2475aef',
//     messagingSenderId: '880329077950',
//     projectId: 'traveladminapp',
//     authDomain: 'traveladminapp.firebaseapp.com',
//     storageBucket: 'traveladminapp.firebasestorage.app',
//     measurementId: 'G-Z0WT4NRZ2Q',
//   );

// }
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcsnDo--MKbIS94agOAnpPhJ0iTeahPk',
    appId: '1:523603037972:web:0f7b3c895ce85f1e15bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    authDomain: 'travelapp-34706.firebaseapp.com',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    measurementId: 'G-MZFG80EXLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlp3Xx8wkItZXPxPhbob9IaYfXFBxkIHE',
    appId: '1:523603037972:android:9b6195a2c9a0d41815bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    storageBucket: 'travelapp-34706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBniiw9-eN2PPBmQUSJOCLmz6siTrlhpY',
    appId: '1:523603037972:ios:624e09fc651961d915bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    iosBundleId: 'com.example.travelappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBniiw9-eN2PPBmQUSJOCLmz6siTrlhpY',
    appId: '1:523603037972:ios:624e09fc651961d915bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    iosBundleId: 'com.example.travelappProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHcsnDo--MKbIS94agOAnpPhJ0iTeahPk',
    appId: '1:523603037972:web:21777363c951791815bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    authDomain: 'travelapp-34706.firebaseapp.com',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    measurementId: 'G-GG1F17JTKZ',
  );
}
