// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcsnDo--MKbIS94agOAnpPhJ0iTeahPk',
    appId: '1:523603037972:web:0f7b3c895ce85f1e15bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    authDomain: 'travelapp-34706.firebaseapp.com',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    measurementId: 'G-MZFG80EXLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlp3Xx8wkItZXPxPhbob9IaYfXFBxkIHE',
    appId: '1:523603037972:android:fed63fff03f693e815bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    storageBucket: 'travelapp-34706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBniiw9-eN2PPBmQUSJOCLmz6siTrlhpY',
    appId: '1:523603037972:ios:49ff731d5e4cb90515bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    androidClientId: '523603037972-5q429t0rt7gqh167lpfatib204s4i80o.apps.googleusercontent.com',
    iosClientId: '523603037972-tv2jeb6rrd62kuusjd2o9vktrc0v81gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBniiw9-eN2PPBmQUSJOCLmz6siTrlhpY',
    appId: '1:523603037972:ios:49ff731d5e4cb90515bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    androidClientId: '523603037972-5q429t0rt7gqh167lpfatib204s4i80o.apps.googleusercontent.com',
    iosClientId: '523603037972-tv2jeb6rrd62kuusjd2o9vktrc0v81gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHcsnDo--MKbIS94agOAnpPhJ0iTeahPk',
    appId: '1:523603037972:web:47007836e84a3c3415bc01',
    messagingSenderId: '523603037972',
    projectId: 'travelapp-34706',
    authDomain: 'travelapp-34706.firebaseapp.com',
    storageBucket: 'travelapp-34706.firebasestorage.app',
    measurementId: 'G-6XBBXNQGPP',
  );
}
